### ISSUE TITLE
No data in Zabbix

### ISSUE THREAD

**Issue by pochtitehhi** [Kencow/Websphere-MQ-Template-for-Zabbix#2]
I've followed your instructions, but unfortunately there is no data from MQ in zabbix. 
There is an error in Discovery rules saying Value should be a JSON object. What could be wrong?
Zabbix version 3.2.1.
I am a newbie with Zabbix so I don't know what information is needed to understand the problem better :)

**Comment by halversonea** [comment]
I'm having the same issue, did you ever figure it out?

Just tracing through all of this it seems like the user running the commands doesn't have access to run MQ commands so the output isn't getting parsed correctly, but the logs aren't very helpful in being certain about this.

**Comment by lod3456** [comment]
@Kencow I am also getting the same error. Do you know what could be wrong?

**Comment by ghost** [comment]
hello guys, @pochtitehhi , @halversonea , @lod3456 
1) you should add zabbix user to mqm group
sudo usermod -a -G mqm zabbix
2) in discover scripts delete \n \t symbols, as example:
```
#!/bin/bash

length_cur=1

mqmarray=(`dspmq|egrep -i "$1"|awk -F\) '{print $1}'|awk -F\( '{print $2}'   2>/dev/null`)
length_mqm=${#mqmarray[@]}

printf "{"
printf  "\"data\":["
for ((i=0;i<$length_mqm;i++))
do
	q_array_c=(`echo "dis ql(*)" |runmqsc ${mqmarray[$i]}|grep "QUEUE("|grep -v SYSTEM|awk -F\) '{print $1}'|awk -F\( '{print $2}' 2>/dev/null`)
	length_q_c=${#q_array_c[@]}

	let "length_all = $length_all + $length_q_c"
done

for ((i=0;i<$length_mqm;i++))
do
        q_array=(`echo "dis ql(*)" |runmqsc ${mqmarray[$i]}|grep "QUEUE("|grep -v SYSTEM|awk -F\) '{print $1}'|awk -F\( '{print $2}' 2>/dev/null`)
        length_q=${#q_array[@]}


	for ((k=0;k<$length_q;k++))

	do
		printf '{'
		printf "\"{#Q_NAME}\":\"${mqmarray[$i]} ${q_array[$k]}\"}"
		if [ $length_cur -lt $[length_all] ];then
                	printf ','
        	fi
		let "length_cur = $length_cur +1"
	done
done

printf  "]"
printf "}"
```
3. after this steps, zabbix-server discover new items and you can monitor websphere queue depth and queue manager status

4. versions
**zabbix-server** version 3.4(ubuntu 16.04)
**websphere mq** in docker
**zabbix-agent** - wget http://repo.zabbix.com/zabbix/3.4/debian/pool/main/z/zabbix/zabbix-agent_3.4.9-1+wheezy_amd64.deb  
dpkg -i zabbix-agent_3.4.9-1+wheezy_amd64.deb

steps:
1. run docker container for dev purpose
sudo docker run \
  --env LICENSE=accept \
  --env MQ_QMGR_NAME=QM1 \
  --publish 1415:1414 \
  --publish 10070:10050 \
  -v /home/nugusbayevkk/Documents/DEV/zabbix/Websphere-MQ-Template-for-Zabbix:/srcfiles \
  --detach \
  ibmcom/mq
2. open access from docker to host
https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container
on host machine:
iptables -A INPUT -i docker0 -j ACCEPT
check zabbix-server 10051 from docker container
3. and follow steps of this tutorial
 https://github.com/Kencow/Websphere-MQ-Template-for-Zabbix

4. and on websphere mq create queue manager, and queues according to ibm documentation

@Kencow , thanks for you :)

**Comment by ghost** [comment]
guys, main problem that zabbix-agent work under zabbix user, and when it try to execute that shell scripts, it return not json value.
so you should give permission on execute, or create zabbix as owner of that shell scritps
sudo chown -R zabbix:zabbix /etc/zabbix/bin/
i forked this repo, and add discovery for websphere mq channels, and status

**Comment by ccyzjjh** [comment]
I use this  shell scritps， it‘s work ok
chmod 777 /etc/zabbix/bin/
chmod 777 /etc/zabbix/bin/*

**Comment by xuelangzhidian** [comment]
我是zabbix新手，zabbix用加入mqm组，执行这些shell脚本都可以获取MQ信息，为什么我上传了模板，不能自动发现；我在配置主机创建主机，添加Template App WebSphere MQ Service模板，发现状态不支持，信息提示 Unsupported item key
![微信图片_20190711201550](https://user-images.githubusercontent.com/48243001/61050086-bdae5500-a418-11e9-8ce7-c8ebf9e700dd.png)

**Comment by Kencow** [comment]
@nugusbayevk Thanks for your update and PR, sorry for my late merge. :-)
