### ISSUE TITLE
unsupported item key for discovery

### ISSUE THREAD

**Issue by OrwinLopes** [Kencow/Websphere-MQ-Template-for-Zabbix#4]
Hi Sir,

i am trying to use the script with Zabbix 4.2.3 & agent running on  AIX 7.1 ...After importing the template i am not able to see any data. the error for discovery rules is "unsupported item key" . 

When i try to run the discovery scripts directly it gives below errors : 

[nxxx@xxa1] /etc/zabbix/bin $ sh discover.sh
discover.sh[5]: syntax error at line 5 : `(' unexpected

Appreciate your help on this

**Comment by OrwinLopes** [comment]
Hi Sir,

 i used this one but gives error :-

[root@xxa1] /etc/zabbix/bin $ /usr/bin/ksh93 mqm_discvr.sh
{"data":[{"{#MQM_NAME}":"PROJ.CLS.SAP.PR"}mqm_discvr.sh[10]: [: $[4-1]: arithmetic syntax error
{"{#MQM_NAME}":"PROJ.CLS.AMC"}mqm_discvr.sh[10]: [: $[4-1]: arithmetic syntax error
{"{#MQM_NAME}":"PROJ.CLS.KBC"}mqm_discvr.sh[10]: [: $[4-1]: arithmetic syntax error
{"{#MQM_NAME}":"PROJ.CLS.TAB"}mqm_discvr.sh[10]: [: $[4-1]: arithmetic syntax error
]}[root@xxa1] /etc/zabbix/bin $

**Comment by Kencow** [comment]
@OrwinLopes 
pls run the script by **bash**, not ksh (AIX's default shell).

**Comment by OrwinLopes** [comment]
i am afraid AIX dont work well with bash.... what modification needs to be done for them to work with ksh ?

**Comment by OrwinLopes** [comment]
same issue with bash as well  :-

[root@xxa1] /etc/zabbix/bin $ ./mqm_discvr.sh
./mqm_discvr.sh[2]: syntax error at line 2 : `(' unexpected
[root@xxa1] /etc/zabbix/bin $ head mqm_discvr.sh
#!/bin/sh

**Comment by Kencow** [comment]
> same issue with bash as well :-
> 
> [root@xxa1] /etc/zabbix/bin $ ./mqm_discvr.sh
> ./mqm_discvr.sh[2]: syntax error at line 2 : `(' unexpected
> [root@xxa1] /etc/zabbix/bin $ head mqm_discvr.sh
> #!/bin/sh

check the sh version:
/bin/sh --version

**Comment by OrwinLopes** [comment]
Hi Sir,

below output 

/patrol/installer $ /bin/sh --version
/usr/bin/sh --version
--version: bad option(s)

**Comment by Kencow** [comment]
I think your sh is not bash but something else (ksh), try run just "bash" command, if fails, pls install bash for AIX first.

**Comment by stfnbrndg** [comment]
Hi @Kencow and thanks for creating this project. 

I get the same "unsupported item key" error on Zabbix 5 on AIX 7.1. Bash is installed, and I see you've made /bin/bash the interpreter in the scripts. The scripts appear to run without syntax errors when run manually, but no dice on getting the data in Discovery Rules.

**Comment by stfnbrndg** [comment]
As a followup for anyone that has this issue - our problem was that we needed to include conf files in the /etc/zabbix_agent.d directory, where mq.conf gets placed:

/etc/zabbix/zabbix_agentd.conf:Include=/etc/zabbix/zabbix_agentd.d/*.conf

**Comment by kadisnadim** [comment]
Hello, please help. I am facing the following error on AIX 7.3 server:

… discovery rule “ISOPRDMQ1:mq_discvr” became not supported: Unsupported item key.
… discovery rule “ISOPRDMQ1:mqm_discvr” became not supported: Unsupported item key.
… discovery rule “ISOPRDMQ1:ch_discvr” became not supported: Unsupported item key.
